export enum actionTypes {
  UI_LOADING = 'UI_LOADING',
  SET_USER_LIST = 'SET_USER_LIST',
  SELECT_USER = 'SELECT_USER',
  DESELECT_USER = 'DESELECT_USER',
  UPDATE_USER = 'UPDATE_USER',
  REMOVE_USER = 'REMOVE_USER',
}
